# This workflow will do a clean install of node dependencies, build the source code and run tests

name: 'SEO'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-production:
    name: 'Generate SEO files'
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: production-01
            host: SSH_HOST_PRODUCTION_01
          - environment: production-02
            host: SSH_HOST_PRODUCTION_02
          - environment: production-03
            host: SSH_HOST_PRODUCTION_03
    steps:
      - uses: actions/checkout@v6
      - name: Setup Wireguard
        uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/wireguard-up@wireguard/v1
        with:
          wg-config-file: ${{ secrets.WG_CONFIG_FILE }}
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v2.0
        with:
          app: "sitemap"
          version: "main"
          environment: "${{ matrix.environment }}"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_APP_DEPLOYER }}
          ssh-host: ${{ secrets[matrix.host] }}
          notify-on-failure: true
          notify-on-success: true
          tchap-url: ${{ secrets.TCHAP_URL }}
          tchap-token: ${{ secrets.TCHAP_TOKEN }}
      - name: Stop Wireguard
        if: always()
        uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/wireguard-down@wireguard/v1
