# This workflow will do a clean install of node dependencies, build the source code and run tests

name: 'SEO'

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 1 10,25 * *'

jobs:
  build:
    name: 'Generate SEO files'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run ./src/index.ts
        run: npm run build
      - name: Compress seo-files
        run: tar czf ./files.tar.gz ./dist
      - name: Archive seo-files
        uses: actions/upload-artifact@v3
        with:
          name: seo-files
          path: |
            ./files.tar.gz

      - name: Notify staging failure only
        if: failure()
        uses: ./.github/actions/notify
        with:
          message: '🚨 ${{ github.event.repository.name }} : deploy SEO files to production failed'
          hook: ${{ secrets.TCHAP_HOOK }}
          id: ${{ secrets.TCHAP_ROOM_ID }}

  notify-deploy-success:
    name: Notify successful deployment
    runs-on: ubuntu-latest
    needs: [deploy-production]

    steps:
      - uses: actions/checkout@v3
      - name: Notify deploy succes
        uses: ./.github/actions/notify
        with:
          message: '✅ ${{ github.event.repository.name }} : successfully deploy SEO files to production'
          hook: ${{ secrets.TCHAP_HOOK }}
          id: ${{ secrets.TCHAP_ROOM_ID }}
